# Generated by Django 2.1.7 on 2019-03-30 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190329_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='modify_date',
            field=models.DateField(auto_now=True, verbose_name='修改日期'),
        ),
    ]
